services:
  - type: web
    name: greenerygrove
    env: node
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y python3 python3-pip
      pip3 install -r requirements.txt
      npm install
    startCommand: npm start
